const taskCards = [
    {
      id: 1,
      title: 'Complete feature integration for task management',
      description: 'Integrate new features into the task management system for enhanced functionality.',
      isComplete: false,
      dueDate: new Date('2024-02-12'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 2,
      title: 'Prepare agenda for team meeting',
      description: 'Create an agenda outlining key topics and updates for the upcoming team meeting.',
      isComplete: true,
      dueDate: new Date('2024-02-15'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 3,
      title: 'Code review for UI improvements',
      description: 'Conduct a thorough code review for recent UI enhancements and provide feedback.',
      isComplete: false,
      dueDate: new Date('2024-02-18'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 4,
      title: 'Test new API endpoints',
      description: 'Perform testing and validation for newly implemented API endpoints in the backend.',
      isComplete: false,
      dueDate: new Date('2024-02-20'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 5,
      title: 'Write release notes for version 1.2.0',
      description: 'Draft release notes highlighting new features and improvements in version 1.2.0.',
      isComplete: false,
      dueDate: new Date('2024-02-22'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 6,
      title: 'Conduct user feedback session',
      description: 'Gather user feedback through a scheduled session to identify areas for improvement.',
      isComplete: true,
      dueDate: new Date('2024-02-25'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 7,
      title: 'Optimize database queries',
      description: 'Review and optimize database queries to enhance overall system performance.',
      isComplete: false,
      dueDate: new Date('2024-02-28'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 8,
      title: 'Design wireframes for new dashboard',
      description: 'Create wireframes and mockups for the upcoming dashboard redesign project.',
      isComplete: false,
      dueDate: new Date('2024-03-02'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 9,
      title: 'Troubleshoot production issues',
      description: 'Investigate and resolve any production issues reported by users or the monitoring system.',
      isComplete: false,
      dueDate: new Date('2024-03-05'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 10,
      title: 'Prepare sprint retrospective',
      description: 'Compile feedback and insights for the sprint retrospective meeting with the team.',
      isComplete: true,
      dueDate: new Date('2024-03-08'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 11,
      title: 'Implement password reset functionality',
      description: 'Add a secure and user-friendly password reset functionality to the authentication system.',
      isComplete: false,
      dueDate: new Date('2024-03-11'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 12,
      title: 'Review and update documentation',
      description: 'Ensure that project documentation is up-to-date with the latest changes and features.',
      isComplete: false,
      dueDate: new Date('2024-03-14'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 13,
      title: 'Create marketing materials for product launch',
      description: 'Design marketing materials and content for the upcoming product launch campaign.',
      isComplete: false,
      dueDate: new Date('2024-03-17'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 14,
      title: 'Optimize frontend performance',
      description: 'Identify and implement optimizations to improve the overall performance of the frontend.',
      isComplete: false,
      dueDate: new Date('2024-03-20'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 15,
      title: 'Coordinate with external vendors',
      description: 'Communicate and coordinate with external vendors for necessary resources and services.',
      isComplete: true,
      dueDate: new Date('2024-03-23'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 16,
      title: 'Plan team-building activities',
      description: 'Organize team-building activities to foster a positive and collaborative work environment.',
      isComplete: false,
      dueDate: new Date('2024-03-26'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 17,
      title: 'Update website content',
      description: 'Review and update content on the company website to reflect the latest information.',
      isComplete: false,
      dueDate: new Date('2024-03-29'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 18,
      title: 'Create training materials for new hires',
      description: 'Develop training materials and resources for onboarding new members to the team.',
      isComplete: true,
      dueDate: new Date('2024-04-01'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 19,
      title: 'Monitor server logs for errors',
      description: 'Regularly check server logs for errors and anomalies, addressing any issues promptly.',
      isComplete: false,
      dueDate: new Date('2024-04-04'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 20,
      title: 'Implement dark mode feature',
      description: 'Add a dark mode feature to the application for enhanced user experience and accessibility.',
      isComplete: false,
      dueDate: new Date('2024-04-07'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 21,
      title: 'Collaborate with UX/UI team on design improvements',
      description: 'Engage with the UX/UI team to implement design improvements based on user feedback.',
      isComplete: true,
      dueDate: new Date('2024-04-10'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 22,
      title: 'Test and debug mobile responsiveness',
      description: 'Thoroughly test and debug the mobile responsiveness of the application on various devices.',
      isComplete: false,
      dueDate: new Date('2024-04-13'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 23,
      title: 'Generate reports for monthly performance analysis',
      description: 'Compile and analyze performance data to generate insightful reports for management.',
      isComplete: false,
      dueDate: new Date('2024-04-16'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 24,
      title: 'Implement multi-language support',
      description: 'Integrate multi-language support to make the application accessible to a global audience.',
      isComplete: true,
      dueDate: new Date('2024-04-19'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 25,
      title: 'Enhance error handling in the backend',
      description: 'Review and enhance error handling mechanisms in the backend for better resilience.',
      isComplete: false,
      dueDate: new Date('2024-04-22'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 26,
      title: 'Organize virtual team-building event',
      description: 'Plan and execute a virtual team-building event to strengthen team connections remotely.',
      isComplete: false,
      dueDate: new Date('2024-04-25'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 27,
      title: 'Conduct security audit for the application',
      description: 'Perform a thorough security audit to identify and address potential vulnerabilities.',
      isComplete: true,
      dueDate: new Date('2024-04-28'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 28,
      title: 'Update user documentation for new features',
      description: 'Revise and update user documentation to reflect the latest features and functionalities.',
      isComplete: false,
      dueDate: new Date('2024-05-01'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 29,
      title: 'Implement automated testing for critical paths',
      description: 'Introduce automated testing procedures for critical paths to improve reliability.',
      isComplete: false,
      dueDate: new Date('2024-05-04'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
    {
      id: 30,
      title: 'Plan and execute customer feedback survey',
      description: 'Create and distribute a survey to gather valuable feedback from users for product improvement.',
      isComplete: true,
      dueDate: new Date('2024-05-07'),
      dateAdded: new Date('2024-01-28T12:34:56.789Z'),
    },
  ];
export default taskCards;